In [1]:
import pandas as pd

df = pd.read_csv(r'D:\Jupyter\Data\auto_ins.csv',encoding='gb2312')
df

,EngSize,Age,Gender,Marital,exp,Owner,vAge,Garage,AntiTFD,import,Loss
0,2.0,56,男,已婚,20,公司,10,有,有防盗装置,进口,0.0
1,1.8,41,男,已婚,20,公司,9,有,无防盗装置,国产,0.0
2,2.0,44,男,未婚,20,公司,8,有,有防盗装置,国产,0.0
3,1.6,56,男,已婚,20,公司,7,有,有防盗装置,国产,0.0
4,1.8,45,男,已婚,20,公司,7,无,无防盗装置,国产,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4228,1.8,22,女,未婚,0,私人,1,有,有防盗装置,国产,976.0
4229,2.5,22,男,未婚,0,私人,1,有,无防盗装置,进口,855.6
4230,1.8,21,男,未婚,0,私人,1,有,无防盗装置,国产,0.0
4231,1.8,21,女,未婚,0,私人,1,有,无防盗装置,进口,3328.0
4232,2.4,21,女,未婚,0,私人,1,有,无防盗装置,进口,1564.0

### 一、Map

将函数套用到Series上的每个元素（elementwise）

官方说明：Series.map: For element-wise operations.

#### 举例：对Loss进行标准化

In [2]:
df['Loss_zscore'] = df['Loss'].map(lambda x: (x-df['Loss'].mean())/df['Loss'].std())
df

,EngSize,Age,Gender,Marital,exp,Owner,vAge,Garage,AntiTFD,import,Loss,Loss_zscore
0,2.0,56,男,已婚,20,公司,10,有,有防盗装置,进口,0.0,-0.232153
1,1.8,41,男,已婚,20,公司,9,有,无防盗装置,国产,0.0,-0.232153
2,2.0,44,男,未婚,20,公司,8,有,有防盗装置,国产,0.0,-0.232153
3,1.6,56,男,已婚,20,公司,7,有,有防盗装置,国产,0.0,-0.232153
4,1.8,45,男,已婚,20,公司,7,无,无防盗装置,国产,0.0,-0.232153
...,...,...,...,...,...,...,...,...,...,...,...,...
4228,1.8,22,女,未婚,0,私人,1,有,有防盗装置,国产,976.0,0.153959
4229,2.5,22,男,未婚,0,私人,1,有,无防盗装置,进口,855.6,0.106328
4230,1.8,21,男,未婚,0,私人,1,有,无防盗装置,国产,0.0,-0.232153
4231,1.8,21,女,未婚,0,私人,1,有,无防盗装置,进口,3328.0,1.084427
4232,2.4,21,女,未婚,0,私人,1,有,无防盗装置,进口,1564.0,0.386576

### 二、Apply

_注意事项：axis=1不可少_

将函数套用到DataFrame上的行和列

官方说明：DataFrame.apply : Apply a function row-/column-wise.

#### 举例：求每位学生三次考试成绩中，最高分和最低分的差值

In [4]:
score = pd.DataFrame([
                    [60,70,50],\
                    [80,79,68],\
                    [63,66,82]], columns = ['First', 'Second', 'Third'])
score

   First  Second  Third
0     60      70     50
1     80      79     68
2     63      66     82

In [6]:
score['dif'] = score.apply(lambda x: x.max()-x.min(),axis=1)
score

   First  Second  Third   dif
0     60      70     50  20.0
1     80      79     68  12.0
2     63      66     82  19.0

#### 也可以在指定的几列中进行求差值

In [12]:
score['dif'] = score[['First','Second','Third']].apply(lambda x: x.max()-x.min(),axis=1)
score

   First  Second  Third  dif
0     60      70     50   20
1     80      79     68   12
2     63      66     82   19

#### 根据已有列生成新的列：计算得出

要对DataFrame的多个列同时进行运算，可以使用apply，例如col3 = col1 + 2 * col2

In [ ]:
df['col3'] = df.apply(lambda x: x['col1'] + 2 * x['col2'], axis=1)

其中x带表当前行，可以通过下标进行索引。

#### 根据已有列生成新的列：判断得出

In [ ]:
def mergeType(a, b):
    if str(a) == 'nan':    # 这里用了isna()、isnull()都不行，暂时转成str()再判断
        b = b
    else:
        b = '催促'
    return b

df_2['callType'] = df_2.apply(lambda x: mergeType(x['urgentType'], x['callType']), axis=1)

### 三、ApplyMap

将函数套用到DataFrame上的每个元素（elementwise）

官方说明：DataFrame.applymap : Apply a function elementwise on a whole DataFrame

#### 举例：将DataFrame中所有字段值为“暂无资料”的改为空值NaN

In [7]:
df.applymap(lambda x: np.nan if x=='暂无资料' else x)

,EngSize,Age,Gender,Marital,exp,Owner,vAge,Garage,AntiTFD,import,Loss,Loss_zscore
0,2.0,56,男,已婚,20,公司,10,有,有防盗装置,进口,0.0,-0.232153
1,1.8,41,男,已婚,20,公司,9,有,无防盗装置,国产,0.0,-0.232153
2,2.0,44,男,未婚,20,公司,8,有,有防盗装置,国产,0.0,-0.232153
3,1.6,56,男,已婚,20,公司,7,有,有防盗装置,国产,0.0,-0.232153
4,1.8,45,男,已婚,20,公司,7,无,无防盗装置,国产,0.0,-0.232153
...,...,...,...,...,...,...,...,...,...,...,...,...
4228,1.8,22,女,未婚,0,私人,1,有,有防盗装置,国产,976.0,0.153959
4229,2.5,22,男,未婚,0,私人,1,有,无防盗装置,进口,855.6,0.106328
4230,1.8,21,男,未婚,0,私人,1,有,无防盗装置,国产,0.0,-0.232153
4231,1.8,21,女,未婚,0,私人,1,有,无防盗装置,进口,3328.0,1.084427
4232,2.4,21,女,未婚,0,私人,1,有,无防盗装置,进口,1564.0,0.386576