In [1]:
import pandas as pd

df = pd.read_csv(r'D:\Jupyter\Data\auto_ins.csv',encoding='gb2312')
df

,EngSize,Age,Gender,Marital,exp,Owner,vAge,Garage,AntiTFD,import,Loss
0,2.0,56,男,已婚,20,公司,10,有,有防盗装置,进口,0.0
1,1.8,41,男,已婚,20,公司,9,有,无防盗装置,国产,0.0
2,2.0,44,男,未婚,20,公司,8,有,有防盗装置,国产,0.0
3,1.6,56,男,已婚,20,公司,7,有,有防盗装置,国产,0.0
4,1.8,45,男,已婚,20,公司,7,无,无防盗装置,国产,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4228,1.8,22,女,未婚,0,私人,1,有,有防盗装置,国产,976.0
4229,2.5,22,男,未婚,0,私人,1,有,无防盗装置,进口,855.6
4230,1.8,21,男,未婚,0,私人,1,有,无防盗装置,国产,0.0
4231,1.8,21,女,未婚,0,私人,1,有,无防盗装置,进口,3328.0
4232,2.4,21,女,未婚,0,私人,1,有,无防盗装置,进口,1564.0

#### 单个生成哑变量

In [2]:
?pd.get_dummies

In [3]:
Owner_merge = pd.get_dummies(df['Owner'],prefix='Owner',drop_first=False)    # drop_first如果把默认的值改为True，则会去掉第一个哑变量
Owner_merge

      Owner_公司  Owner_政府  Owner_私人
0            1         0         0
1            1         0         0
2            1         0         0
3            1         0         0
4            1         0         0
...        ...       ...       ...
4228         0         0         1
4229         0         0         1
4230         0         0         1
4231         0         0         1
4232         0         0         1

[4233 rows x 3 columns]

##### 合并原df和新的哑变量

pd.concat合并后只保留一个index

In [4]:
df = pd.concat([df,Owner_merge],axis=1)
df

,EngSize,Age,Gender,Marital,exp,Owner,vAge,Garage,AntiTFD,import,Loss,Owner_公司,Owner_政府,Owner_私人
0,2.0,56,男,已婚,20,公司,10,有,有防盗装置,进口,0.0,1,0,0
1,1.8,41,男,已婚,20,公司,9,有,无防盗装置,国产,0.0,1,0,0
2,2.0,44,男,未婚,20,公司,8,有,有防盗装置,国产,0.0,1,0,0
3,1.6,56,男,已婚,20,公司,7,有,有防盗装置,国产,0.0,1,0,0
4,1.8,45,男,已婚,20,公司,7,无,无防盗装置,国产,0.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4228,1.8,22,女,未婚,0,私人,1,有,有防盗装置,国产,976.0,0,0,1
4229,2.5,22,男,未婚,0,私人,1,有,无防盗装置,进口,855.6,0,0,1
4230,1.8,21,男,未婚,0,私人,1,有,无防盗装置,国产,0.0,0,0,1
4231,1.8,21,女,未婚,0,私人,1,有,无防盗装置,进口,3328.0,0,0,1
4232,2.4,21,女,未婚,0,私人,1,有,无防盗装置,进口,1564.0,0,0,1

#### 批量生成哑变量（把字符变量转成数值变量）

In [6]:
df2 = pd.get_dummies(df)
df2

,EngSize,Age,exp,vAge,Loss,Owner_公司,Owner_政府,Owner_私人,Gender_女,Gender_男,...,Marital_未婚,Owner_公司,Owner_政府,Owner_私人,Garage_无,Garage_有,AntiTFD_无防盗装置,AntiTFD_有防盗装置,import_国产,import_进口
0,2.0,56,20,10,0.0,1,0,0,0,1,...,0,1,0,0,0,1,0,1,0,1
1,1.8,41,20,9,0.0,1,0,0,0,1,...,0,1,0,0,0,1,1,0,1,0
2,2.0,44,20,8,0.0,1,0,0,0,1,...,1,1,0,0,0,1,0,1,1,0
3,1.6,56,20,7,0.0,1,0,0,0,1,...,0,1,0,0,0,1,0,1,1,0
4,1.8,45,20,7,0.0,1,0,0,0,1,...,0,1,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4228,1.8,22,0,1,976.0,0,0,1,1,0,...,1,0,0,1,0,1,0,1,1,0
4229,2.5,22,0,1,855.6,0,0,1,0,1,...,1,0,0,1,0,1,1,0,0,1
4230,1.8,21,0,1,0.0,0,0,1,0,1,...,1,0,0,1,0,1,1,0,1,0
4231,1.8,21,0,1,3328.0,0,0,1,1,0,...,1,0,0,1,0,1,1,0,0,1
4232,2.4,21,0,1,1564.0,0,0,1,1,0,...,1,0,0,1,0,1,1,0,0,1